services:
  postgres:
    image: postgres:16
    container_name: UniversityPortal-db
    environment:
      POSTGRES_DB: UniversityPortal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tanid2715!
    ports:
      - "5432:5432"
