### Registration API Test Requests

### 1. Get available course offerings for a semester
GET http://localhost:8090/api/registration/offerings?semester=Spring%2026&courseCode=CSC
Authorization: Basic user 69dd5140-0a36-44d7-a7f2-3297830bcd1a
Accept: application/json


POST http://localhost:8090/api/registration/register
Content-Type: application/json

{
  "studentId": 1,
  "offeringId": 1
}

### TODO: Test this endpoint
### Drop a course
POST http://localhost:8090/api/registration/drop
Content-Type: application/json

{
  "studentId": 1,
  "offeringId": 1
}