### Registration API Test Requests

###Variables
@baseUrl = http://localhost:8090/api/registration
@studentId = 1
@offeringId = 1

### 1. Get available course offerings for a semester
GET {{baseUrl}}/offerings?semester=Spring%2026&courseCode=CSC
Authorization: Basic user pass
Accept: application/json


### 2. Get registered courses for a student
POST {{baseUrl}}/register
Authorization: Basic user pass
Content-Type: application/json

{
  "studentId": {{studentId}},
  "offeringId": {{offeringId}}
}

### 3. Drop a course
POST {{baseUrl}}/drop
Authorization: Basic user pass
Content-Type: application/json

{
  "studentId": {{studentId}},
  "offeringId": {{offeringId}}
}

### 4. Add to wishlist
POST {{baseUrl}}/wishlist/add
Authorization: Basic user pass
Content-Type: application/json

{
  "studentId": {{studentId}},
  "offeringId": {{offeringId}}
}

### 5. Remove from wishlist
DELETE {{baseUrl}}/wishlist/remove
Authorization: Basic user pass
Content-Type: application/json

{
  "studentId": {{studentId}},
  "offeringId": {{offeringId}}
}

### 6. Register all from wishlist
POST {{baseUrl}}/wishlist/register-all?studentId={{studentId}}&term=Fall%2026
Authorization: Basic user pass
Content-Type: application/json
