# H2 in-memory DB (acts more like Postgres)
spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Let Hibernate create tables from your entities for the test run
spring.jpa.hibernate.ddl-auto=create-drop

#Helpful during setup/debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true